#!/bin/bash

#SSH Authorization Server Script via Github
#---
#This script utilizies AuthorizedKeysCommand in sshd_config to
#authorize clients by utilizing githubs public keys. Simply upload
#a new key to github to authorize a client to your servers.
#

github_user=USERNAME
auth_server=https://github.com/$github_user.keys
key_paths=/root/.ssh/authorized_keys2,/home/user1/.ssh/authorized_keys2 # Comma Seperated Paths

keys=$(curl -s $auth_server)
if [[ ! $(echo "$keys" | grep ssh-) ]]; then
  echo Auth Server Unreachable
  exit
fi

IFS=,
for user_path in $key_paths; do
  split=$(echo "$user_path" | sed 's|/| |g')
  if [[ $(echo $split | awk '{print $1}') == root ]]; then user=root; else user=$(echo $split | awk '{print $2}'); fi
  if [[ ! -f $user_path ]] || grep -q "ssh" $user_path ; then
    echo $keys > $user_path
    sed -i '1i \# Generated by auth.sh' $user_path
    chmod 600 $user_path
    chown $user:$user $user_path
  fi
done
unset IFS

# Outputs keys to sshd
echo $keys
